#!/bin/bash
# build_runtime.sh: sync three Lua layers + web into runtime/ (plain sources).
# Output: runtime/**/*.lua + runtime/web/ (plain copy of luan/web) + mime.types
#
# runtime/ is a BUILD output directory — do not hand-edit.
# Edit sources under:
#   luan_mac/lua-apple/luafan/modules  (layer 1)
#   luan_mac/webase/                   (layer 2 submodule)
#   luan_mac/luan/                     (layer 3 submodule)
# then re-run this script.
# Web is rsynced as-is (no JS minify / no Node/terser).
# Host loads runtime/core.lua (see LuanMac/LuaBridge.m).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

RUNTIME_DIR="$PROJECT_ROOT/runtime"

LAYER1="$(cd "$PROJECT_ROOT/lua-apple/luafan/modules" && pwd)"
LAYER2="$(cd "$PROJECT_ROOT/webase" && pwd)"
LAYER3="$(cd "$PROJECT_ROOT/luan" && pwd)"

if [ ! -d "$LAYER1" ] || [ ! -d "$LAYER2" ] || [ ! -d "$LAYER3" ]; then
    echo "[build] ERROR: missing layer dir(s)" >&2
    echo "  LAYER1=$LAYER1" >&2
    echo "  LAYER2=$LAYER2" >&2
    echo "  LAYER3=$LAYER3" >&2
    exit 1
fi

mkdir -p "$RUNTIME_DIR"

# ---- Stage merged Lua tree (later layers overwrite earlier; Docker COPY semantics) ----
STAGE="$RUNTIME_DIR/.build-lua-stage"
rm -rf "$STAGE"
mkdir -p "$STAGE"

# Shared rsync filters: only runtime-ish tree (*.lua + dirs). Skip VCS/tests/docs/docker noise.
RSYNC_LUA_EXCLUDES=(
    --exclude '.git/'
    --exclude '.github/'
    --exclude '.claude/'
    --exclude '.DS_Store'
    --exclude 'tests/'
    --exclude 'docs/'
    --exclude 'tmp/'
    --exclude 'conversations_history/'
    --exclude 'curl-impersonate/'
    --exclude 'gcm/'
    --exclude 'web/'
    --exclude 'Dockerfile'
    --exclude 'Dockerfile.*'
    --exclude 'docker-compose.yml'
    --exclude 'docker-compose.*.yml'
    --exclude 'nginx.conf'
    --exclude '.dockerignore'
    --exclude '.gitignore'
    --exclude 'README.md'
    --exclude 'README*'
    --exclude 'CLAUDE.md'
    --exclude 'CODE_STATS.md'
    --exclude 'TODO.md'
)

echo "[build] layer1 (luafan modules) → stage"
rsync -a "${RSYNC_LUA_EXCLUDES[@]}" "$LAYER1/" "$STAGE/"

echo "[build] layer2 (webase) → stage"
rsync -a "${RSYNC_LUA_EXCLUDES[@]}" "$LAYER2/" "$STAGE/"

echo "[build] layer3 (luan) → stage"
rsync -a "${RSYNC_LUA_EXCLUDES[@]}" \
    --exclude 'static/' \
    --exclude 'skills/' \
    --exclude 'module/' \
    --exclude 'native/' \
    --exclude 'handle/test_*.lua' \
    "$LAYER3/" "$STAGE/"

# Deploy test-only HTTP handlers only for the local integration app.
if [ "${LUAN_TEST_ENV:-0}" = "1" ]; then
    echo "[build] test handlers → stage/handle"
    rsync -a "$LAYER3/handle/test_"*.lua "$STAGE/handle/"
fi

# Deploy pure Lua unit sources as test-only runtime assets. They must not live
# under handle/, because route loading executes every handle at startup.
mkdir -p "$STAGE/unit"
for UNIT_SOURCE in "$LAYER3"/tests/test_*.lua; do
    cp "$UNIT_SOURCE" "$STAGE/unit/$(basename "$UNIT_SOURCE")"
done

if [ ! -f "$STAGE/core.lua" ]; then
    echo "[build] ERROR: staged tree missing core.lua (expected from webase)" >&2
    exit 1
fi

# Drop retired bundle artifacts from stage if any source ever shipped them
rm -f "$STAGE/core.dll" "$STAGE/core.luac" \
    "$STAGE/_amalgamated.lua" "$STAGE/_amalgamated.luac"

# ---- Publish stage into runtime/ (preserve web/, cacert, local sites data) ----
echo "[build] stage → runtime/ (delete stale lua; keep web/ cacert sites)"
# Native scanner sources belong to luan/native and are built separately; never keep stale runtime/native files.
rm -rf "$RUNTIME_DIR/native"
rsync -a --delete \
    --exclude 'web/' \
    --exclude 'cacert.pem' \
    --exclude 'sites/' \
    --exclude '.build-from-luan' \
    --exclude '.build-lua-stage/' \
    "$STAGE/" "$RUNTIME_DIR/"

rm -rf "$STAGE"

# Explicitly remove any leftover bundle files at runtime root
rm -f "$RUNTIME_DIR/core.dll" "$RUNTIME_DIR/core.luac" \
    "$RUNTIME_DIR/_amalgamated.lua" "$RUNTIME_DIR/_amalgamated.luac"
# Legacy per-file .dll modules (if any)
find "$RUNTIME_DIR" -type f -name '*.dll' -delete 2>/dev/null || true

# mime.types: last layer that has it wins (same as old build)
for LAYER in "$LAYER1" "$LAYER2" "$LAYER3"; do
    if [ -f "$LAYER/mime.types" ]; then
        cp "$LAYER/mime.types" "$RUNTIME_DIR/mime.types"
    fi
done
# webase ships mime.types at repo root
if [ -f "$LAYER2/mime.types" ]; then
    cp "$LAYER2/mime.types" "$RUNTIME_DIR/mime.types"
fi

# ---- Web: plain rsync from luan only (no minify) ----
echo "[build] web (luan/web) → runtime/web (plain copy)"
mkdir -p "$RUNTIME_DIR/web"
rsync -a --delete --exclude '.*' --exclude '*.map' \
    "$LAYER3/web/" "$RUNTIME_DIR/web/"

printf '%s\n' \
    "Generated by luan_mac/scripts/build_runtime.sh from luafan modules + webase + luan" \
    "Plain Lua tree (core.lua entry). DO NOT EDIT runtime/ — rebuild after source changes." \
    "Web: plain copy of luan/web/ (no JS minify)." \
    > "$RUNTIME_DIR/web/.build-from-luan"

# Build stamp: single UTC timestamp used at runtime to expose which build a
# running process loaded (X-Luan-Build header). Helps detect "disk updated but
# process not restarted". Not a version number — luan is one whole.
date -u '+%Y-%m-%dT%H:%M:%SZ' > "$RUNTIME_DIR/.build-stamp"

LUA_COUNT="$(find "$RUNTIME_DIR" -type f -name '*.lua' ! -path '*/web/*' | wc -l | tr -d ' ')"
JS_COUNT="$(find "$RUNTIME_DIR/web" -type f -name '*.js' | wc -l | tr -d ' ')"
echo "[build] web: $JS_COUNT JS file(s) (plain)"
echo "[build] done: $LUA_COUNT lua file(s) under runtime/ + runtime/web/ (entry: core.lua)"

# Optional: deploy to workspace runtime/ for local testing
# Set DEPLOY_RUNTIME e.g. ~/SAPDevelop/luan_ws/runtime
DEPLOY_RUNTIME="${DEPLOY_RUNTIME:-}"
if [ -n "$DEPLOY_RUNTIME" ]; then
    # Remove stale symlink or directory
    if [ -L "$DEPLOY_RUNTIME" ]; then
        rm -f "$DEPLOY_RUNTIME"
    elif [ -d "$DEPLOY_RUNTIME" ]; then
        rm -rf "$DEPLOY_RUNTIME"
    fi
    mkdir -p "$DEPLOY_RUNTIME"
    rsync -a --delete "$RUNTIME_DIR/" "$DEPLOY_RUNTIME/"
    echo "[build] deployed → $DEPLOY_RUNTIME"
fi
